-- Generato da Oracle SQL Developer Data Modeler 4.1.1.888
--   in:        2016-02-21 19:56:41 CET
--   sito:      Oracle Database 11g
--   tipo:      Oracle Database 11g




CREATE TABLE SPREADEASY_TEST_RESULTS
  (
    TEST_NO        NUMBER (10) NOT NULL ,
    TEST_UNIT_NAME VARCHAR2 (100 CHAR) ,
    STYLE_ID       NUMBER (2) NOT NULL ,
    SPREADSHEET XMLTYPE ,
    START_DATE_TIME TIMESTAMP (3) NOT NULL ,
    EXECUTION_TIME INTERVAL DAY (0) TO SECOND (9)
  )
  XMLTYPE COLUMN SPREADSHEET STORE AS BINARY XML
  (
    STORAGE ( PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 BUFFER_POOL DEFAULT ) RETENTION ENABLE STORAGE IN ROW NOCACHE
  ) ;
COMMENT ON TABLE SPREADEASY_TEST_RESULTS
IS
  'Repository of the spreadsheets generated by the tests' ;
  COMMENT ON COLUMN SPREADEASY_TEST_RESULTS.TEST_NO
IS
  'Test number (sequence generated)' ;
  COMMENT ON COLUMN SPREADEASY_TEST_RESULTS.TEST_UNIT_NAME
IS
  'Unit test name' ;
  COMMENT ON COLUMN SPREADEASY_TEST_RESULTS.STYLE_ID
IS
  'XSLT Style ID: 1=Excel 2002 (.xls)' ;
  COMMENT ON COLUMN SPREADEASY_TEST_RESULTS.SPREADSHEET
IS
  'Spreadsheet XML file' ;
  COMMENT ON COLUMN SPREADEASY_TEST_RESULTS.START_DATE_TIME
IS
  'Test execution start date and time' ;
  COMMENT ON COLUMN SPREADEASY_TEST_RESULTS.EXECUTION_TIME
IS
  'Time elapsed to complete the execution of th "build" procedure' ;
ALTER TABLE SPREADEASY_TEST_RESULTS ADD CONSTRAINT SPREADEASY_TEST_RESULTS_PK PRIMARY KEY ( TEST_NO ) ;


CREATE SEQUENCE SPREADEASY_TEST_RESULTS_SQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER SPREADEASY_TEST_RESULTS_SQTR BEFORE
  INSERT ON SPREADEASY_TEST_RESULTS FOR EACH ROW WHEN (NEW.TEST_NO IS NULL) BEGIN :NEW.TEST_NO := SPREADEASY_TEST_RESULTS_SQ.NEXTVAL;
END;
/


-- Report sintetico di Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                             1
-- CREATE INDEX                             0
-- ALTER TABLE                              1
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           1
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          1
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
