DELETE FROM SPREADEASY_LOCALES ;

INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('en', 'GB', '£', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Page');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('en', 'IR', '€', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Page');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('en', 'US', '$', 'lr_tb', 'MM/DD/YYYY', 'HH24.MI.SS', 'Page');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('en', 'AU', '$', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Page');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('en', 'NZ', '$', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Page');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('en', 'ZA', '$', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Page');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('af', 'ZA', '$', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Bladsy');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('en', 'CA', '$', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Page');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('fr', 'CA', '$', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Page');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('it', 'IT', '€', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Pagina');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('it', 'SM', '€', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Pagina');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('it', 'CH', 'CHF', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Pagina');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('fr', 'CH', 'CHF', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Page');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('de', 'CH', 'CHF', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Seite');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('fr', 'FR', '€', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Page');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('de', 'DE', '€', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Seite');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('de', 'AT', '€', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Seite');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('de', 'LI', '€', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Seite');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('fr', 'BE', '€', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Page');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('pt', 'PT', '€', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Página');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('es', 'ES', '€', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Página');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('ca', 'ES', '€', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Pàgina');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('ca', 'AD', '€', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Pàgina');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('nl', 'NL', '€', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Page');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('fr', 'LU', '€', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Page');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('da', 'DK', 'kr', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Side');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('nn', 'NO', 'kr', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Side');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('nb', 'NO', 'kr', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Side');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('sv', 'SE', 'kr', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Sida');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('fi', 'FI', '€', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Sivu');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('is', 'IS', 'kr', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Síðu');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('mt', 'MT', '€', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Paġna');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('el', 'GR', '€', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'σελίδα');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('el', 'CY', '€', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'σελίδα');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('sq', 'AL', 'Lek', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Faqe');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('mk', 'MK', 'ден', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'страница');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('sl', 'SI', '€', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Stran');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('hr', 'HR', '€', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Stranica');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('sk', 'SK', '€', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Strana');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('cz', 'CZ', 'Kč', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Strana');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('hu', 'HU', 'ft', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Oldal');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('ro', 'RO', 'lei', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Pagină');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('pl', 'PL', 'zł', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Strona');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('ru', 'RU', '₽', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'страница');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('uk', 'UA', '₴', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'сторінка');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('be', 'BY', 'p.', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'старонка');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('et', 'EE', '€', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Lehekülg');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('lv', 'LV', '€', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Lappuse');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('lt', 'LT', '€', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Puslapis');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('pt', 'BR', 'R$', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Página');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('es', 'AR', '$', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Página');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('es', 'UY', '$U', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Página');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('es', 'PY', 'Gs', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Página');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('es', 'PE', 'S/.', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Página');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('es', 'EC', '$', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Página');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('es', 'VE', 'Bs', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Página');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('es', 'CL', '$', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Página');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('es', 'MX', '$', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'Página');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('ja', 'JP', '¥', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'ページ');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('zh', 'CN', '¥', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', '页');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('zh', 'TW', 'NT$', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', '頁');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('ko', 'KR', '₩', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', '페이지');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('ko', 'KP', '₩', 'lr_tb', 'DD/MM/YYYY', 'HH24.MI.SS', '페이지');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('he', 'IL', '₪', 'rl_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'דף');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('ar', 'SA', '﷼', 'rl_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'صفحة');
INSERT INTO SPREADEASY_LOCALES 
(LANGUAGE, TERRITORY, CURRENCY_SYMBOL, WRITING_MODE, DATE_FORMAT, TIME_FORMAT, PAGE)
VALUES
('fa', 'IR', '﷼', 'rl_tb', 'DD/MM/YYYY', 'HH24.MI.SS', 'صفحه');

COMMIT;
