

create table spreadeasy_styles (
   style_id       NUMBER(4)   primary key spreadeasy_styles$pk,
   description    VARCHAR2(64)  not null,
   document       XMLType
);

comment on table spreadeasy_styles is 'XSLT documents to transform a XML document into a SpreadSheet';
comment on column spreadeasy_styles.style_id is 'SpreadSheet Style ID';
comment on column spreadeasy_styles.description is 'Description of the spreadsheet style you''ll get';
comment on column spreadeasy_styles.document is 'XSLT document';



create sequence spreadeasy_spreadsheet_seq MINVALUE 1 MAXVALUE 9999999999 CYCLE;

create table spreadeasy_wrk (
   spreadsheet_id     NUMBER(10) NOT NULL,
   worksheet_id       NUMBER(4) NOT NULL,
   rowset             XMLType
);

comment on table spreadeasy_wrk is 'Temporary staging area for generated XML documents';
comment on column spreadeasy_wrk.spreadsheet_id is 'Unique ID of the SpreadSheets generated by Spreadeasy';
comment on column spreadeasy_wrk.worksheet_id is 'Sequence identifying each Worksheet in a SpreadSheet';
comment on column spreadeasy_wrk.rowset is 'XML document to be wrapped in the Worksheet';


