-- Generato da Oracle SQL Developer Data Modeler 4.1.1.888
--   in:        2016-04-28 21:29:37 CEST
--   sito:      Oracle Database 11g
--   tipo:      Oracle Database 11g




DROP TABLE SPREADEASY_BUILDERS CASCADE CONSTRAINTS ;

DROP TABLE SPREADEASY_LOCALES CASCADE CONSTRAINTS ;

DROP TABLE SPREADEASY_STYLES CASCADE CONSTRAINTS ;

DROP TABLE SPREADEASY_WRK CASCADE CONSTRAINTS ;

CREATE TABLE SPREADEASY_BUILDERS
  (
    STYLE_ID    NUMBER (3) NOT NULL ,
    STEP        NUMBER (3) NOT NULL ,
    BILDER_TYPE VARCHAR2 (3 CHAR) NOT NULL ,
    XML_DOC XMLTYPE ,
    BUILDER_DOC CLOB ,
    OUT_PATH VARCHAR2 (255 CHAR) NOT NULL
  )
  XMLTYPE COLUMN XML_DOC STORE AS BINARY XML
  (
    STORAGE ( PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 BUFFER_POOL DEFAULT ) RETENTION ENABLE STORAGE IN ROW NOCACHE
  ) ;
COMMENT ON COLUMN SPREADEASY_BUILDERS.STEP
IS
  'Building step number' ;
  COMMENT ON COLUMN SPREADEASY_BUILDERS.BILDER_TYPE
IS
  'Builder type' ;
  COMMENT ON COLUMN SPREADEASY_BUILDERS.XML_DOC
IS
  'XML Document, usually a XSL' ;
  COMMENT ON COLUMN SPREADEASY_BUILDERS.BUILDER_DOC
IS
  'File Content' ;
  COMMENT ON COLUMN SPREADEASY_BUILDERS.OUT_PATH
IS
  'Output path' ;
ALTER TABLE SPREADEASY_BUILDERS ADD CONSTRAINT SPREADEASY_BUILDERS_CK_1 CHECK (BUILDER_TYPE IN ('TXT', 'XSL', 'XML')) ;
ALTER TABLE SPREADEASY_BUILDERS ADD CONSTRAINT SPREADEASY_BUILDERS_PK PRIMARY KEY ( STYLE_ID, STEP ) ;


CREATE TABLE SPREADEASY_LOCALES
  (
    LANGUAGE        VARCHAR2 (2 CHAR) NOT NULL ,
    TERRITORY       VARCHAR2 (5 CHAR) NOT NULL ,
    CURRENCY_SYMBOL VARCHAR2 (3 CHAR) NOT NULL ,
    WRITING_MODE    VARCHAR2 (10 CHAR) NOT NULL ,
    DATE_FORMAT     VARCHAR2 (16 CHAR) NOT NULL ,
    TIME_FORMAT     VARCHAR2 (10 CHAR) NOT NULL ,
    PAGE            VARCHAR2 (20 CHAR) NOT NULL
  ) ;
COMMENT ON COLUMN SPREADEASY_LOCALES.LANGUAGE
IS
  'Language ISO-639-1 code' ;
  COMMENT ON COLUMN SPREADEASY_LOCALES.PAGE
IS
  'Translation of the word "Page" ' ;
ALTER TABLE SPREADEASY_LOCALES ADD CONSTRAINT SPREADEASY_LOCALES_PK PRIMARY KEY ( LANGUAGE, TERRITORY ) ;


CREATE TABLE SPREADEASY_STYLES
  (
    STYLE_ID    NUMBER (3) NOT NULL ,
    DESCRIPTION VARCHAR2 (60 CHAR) NOT NULL
  ) ;
COMMENT ON COLUMN SPREADEASY_STYLES.STYLE_ID
IS
  'XSLT ID ' ;
  COMMENT ON COLUMN SPREADEASY_STYLES.DESCRIPTION
IS
  'XSLT description' ;
ALTER TABLE SPREADEASY_STYLES ADD CONSTRAINT SPREADEASY_STYLES_PK PRIMARY KEY ( STYLE_ID ) ;


CREATE TABLE SPREADEASY_WRK
  (
    SPREADSHEET_ID NUMBER (10) NOT NULL ,
    WORKSHEET_ID   NUMBER (4) NOT NULL ,
    DOCUMENT XMLTYPE NOT NULL
  )
  XMLTYPE COLUMN DOCUMENT STORE AS BINARY XML
  (
    STORAGE ( PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 BUFFER_POOL DEFAULT ) RETENTION ENABLE STORAGE IN ROW NOCACHE
  ) ;
COMMENT ON TABLE SPREADEASY_WRK
IS
  'Staging area to temporarily host the data to be used to create a spreadsheet' ;
  COMMENT ON COLUMN SPREADEASY_WRK.SPREADSHEET_ID
IS
  'Unique ID of any spreadsheet creaded by Spreadeasy' ;
  COMMENT ON COLUMN SPREADEASY_WRK.WORKSHEET_ID
IS
  'Worksheet number within the spreadsheet. Worksheets are numbered starting from 1' ;
  COMMENT ON COLUMN SPREADEASY_WRK.DOCUMENT
IS
  'Query result as an XML document to be transformed to a Worksheet content' ;


ALTER TABLE SPREADEASY_BUILDERS ADD CONSTRAINT SPREADEASY$BUILDERS_STYLES_FK FOREIGN KEY ( STYLE_ID ) REFERENCES SPREADEASY_STYLES ( STYLE_ID ) ;


-- Report sintetico di Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             0
-- ALTER TABLE                              5
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
